#!/usr/bin/env python3
"""Regenerate Homepage's bookmarks.yaml from homelab-infra/registry.yaml.

Every registry service with a `dns` name becomes a link in a "Homelab"
bookmarks group. Hand-written bookmarks in bookmarks.static.yaml are kept
and appended after it. Only writes when the output actually changes.

Env:
  REGISTRY_PATH        registry.yaml to read (default /registry.yaml)
  CONFIG_DIR           Homepage config dir (default /config)
  BOOKMARKS_EXCLUDE    comma-separated service keys to leave out
  DRY_RUN=true         print the result instead of writing it
"""
import os
import sys

import yaml

GROUP = "Homelab"
HEADER = (
    "# GENERATED by jobs/bookmarks-sync from homelab-infra/registry.yaml - do\n"
    "# not edit. Hand-written bookmarks go in bookmarks.static.yaml.\n"
)


def title(key: str) -> str:
    # Short parts are acronyms (ci, rtx) - upper-case them rather than "Ci".
    return " ".join(part.upper() if len(part) <= 3 else part.capitalize() for part in key.split("-"))


def abbr(key: str) -> str:
    parts = key.split("-")
    return (parts[0][0] + parts[1][0] if len(parts) > 1 else key[:2]).upper()


def main() -> int:
    print("START bookmarks-sync")
    registry_path = os.environ.get("REGISTRY_PATH", "/registry.yaml")
    config_dir = os.environ.get("CONFIG_DIR", "/config")
    exclude = {s.strip() for s in os.environ.get("BOOKMARKS_EXCLUDE", "").split(",") if s.strip()}
    dry_run = os.environ.get("DRY_RUN", "").lower() == "true"

    with open(registry_path, encoding="utf-8") as f:
        services = (yaml.safe_load(f) or {}).get("services") or {}
    if not services:
        print(f"ERROR: no services found in {registry_path}", file=sys.stderr)
        return 1

    links = [
        {title(key): [{"abbr": abbr(key), "href": f"https://{svc['dns']}/", "description": svc["dns"]}]}
        for key, svc in sorted(services.items())
        if svc.get("dns") and key not in exclude
    ]
    groups = [{GROUP: links}]

    static_path = os.path.join(config_dir, "bookmarks.static.yaml")
    if os.path.exists(static_path):
        with open(static_path, encoding="utf-8") as f:
            groups += yaml.safe_load(f) or []

    output = HEADER + yaml.safe_dump(groups, sort_keys=False, default_flow_style=False)

    out_path = os.path.join(config_dir, "bookmarks.yaml")
    if dry_run:
        print(output)
        print(f"END bookmarks-sync: DRY_RUN, {len(links)} links")
        return 0

    try:
        with open(out_path, encoding="utf-8") as f:
            current = f.read()
    except FileNotFoundError:
        current = None
    if current == output:
        print(f"END bookmarks-sync: unchanged, {len(links)} links")
        return 0

    tmp_path = out_path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(output)
    os.replace(tmp_path, out_path)
    print(f"END bookmarks-sync: wrote {out_path}, {len(links)} links")
    return 0


if __name__ == "__main__":
    sys.exit(main())
